### ISSUE TITLE
Verzögerung

### ISSUE THREAD

**Issue by robug** [superhero1/FruitField#18]
Aufgrund fehlenden Codes der Logik des Spielfeldes kann der heutige Milestone unter Umständen nicht erreicht werden. Wir versuchen dies heute Morgen zu regeln.

**Comment by superhero1** [comment]
Wenn jeder, der gerade am Arbeiten ist, seinen aktuellen Branch hochlädt und nach jeder Programmierung aktualisiert, könnte man gemeinsam eine Lösung erarbeiten.
