### ISSUE TITLE
Test Device in Eclipse

### ISSUE THREAD

**Issue by Klix23** [superhero1/FruitField#2]
Hallo ihr Lieben,

bin mit der GUI schon relativ weit gekommen. Würde sie nun gerne auch auf einem Testgerät anschauen bevor ich den derzeitigen Stand hochlade. 
Wie soll denn das Test-Device für den Emulator in eclipse am besten konfiguriert sein (Version, Bildschirmgröße,etc.)?

Viele Grüße,
Angie

**Comment by superhero1** [comment]
Version: siehe AndroidManifest.xml Zeile 7-9:
`<uses-sdk
        android:minSdkVersion="14"
        android:targetSdkVersion="22" />`,

Nexus 4 kann man als Device auswählen und die RAM-Größe gerne nach unten anpassen (optional).
