### ISSUE TITLE
Upload UML-Klassendiagramm

### ISSUE THREAD

**Issue by superhero1** [superhero1/FruitField#27]

**Comment by superhero1** [comment]
Das UML-Diagramm ist falsch. Bitte korrigieren.

**Comment by superhero1** [comment]
Reopen ist 1 Woche alt, bitte Status melden - _push_

**Comment by JuliaLF** [comment]
Habe das UML-Diagramm gerade nochmal hochgeladen, sieht aus, als hätte es dieses Mal geklappt! :)

**Comment by superhero1** [comment]
Ich denke man kann das so nicht machen. Die ganze rechte Seite würde ich rausschmeißen, das sind nur die GUI-Elemente und die sind ja nicht entsprechend zuordenbar. Das Tool ist für Java-Code und eignet sich nicht so für Android-Applikationen. Daher Android-spezifische Elemente der App weglassen, die nichts mit dem funktionellen Programmcode zu tun haben. Einverstanden?

**Comment by superhero1** [comment]
Bzw. die Buttons sind schon wichtig. Da müsstest du die Klasse entsprechend benennen.

**Comment by superhero1** [comment]
Layout wäre noch sinnvoll, da kannst du dich auch mit @Klix23 absprechen.

**Comment by superhero1** [comment]
@JuliaLF bitte versuche es ausnahmsweise direkt in den master-Branch zu committen und zu pushen.
