### ISSUE TITLE
Aufgabenabgrenzung

### ISSUE THREAD

**Issue by Klix23** [superhero1/FruitField#3]
Hi,

wer programmiert denn die Button-Funktionen (Willkommen-Seite/Spielregeln)?
Ist das schon Logik (Ronja, Maxim) oder noch GUI (ich)?

Viele Grüße,
Angie

**Comment by TexModel** [comment]
Hallo,

das Layout und Screens würde ich noch zu GUI zählen, die Funktionen übernehmen wir.

Viele Grüße,
Maxim

**Comment by superhero1** [comment]
*Edit: Frage entfernt.*
