### ISSUE TITLE
Rückmeldung Variablen

### ISSUE THREAD

**Issue by Klix23** [superhero1/FruitField#4]
Huhu Ronja,

würde die Variablen der GUI gerne schon endgültig belegen.
Kannst du mir schon sagen, wie ihr folgende benannt haben wollt?

1.) Spielfelder (GridLayout)
2.) String für die Zeit
3.) String für den Klickzähler
4.) Buttons

Liebe Grüße,
Angie

**Comment by TexModel** [comment]
Hallo Angie,

1) die Spielfelder (also die einzelnen klickbaren Elemente) haben den Namen "Beet"
2) für die Zeit würde ich "Spielzeit" wählen
3) "Klicks"
4) für die Buttons die Namen der Buttons, oder gibt es da Einwände?

Viele Grüße

**Comment by superhero1** [comment]
Die Klicks sollten kein String sein.

Besser ist es hier gleich einen **konkreten Namen** für jede Variable und den Datentyp zu definieren.

**Comment by TexModel** [comment]
Feld11: Beet 
Hierbei ist nach "Feld" die Zeile und Spalte des Elements angegeben

strZeit : string

intKlicks: int

btnSpielen: button
btnRegeln: button
btnZurück: button

**Comment by superhero1** [comment]
**Korrektur Datentypen**
btnFeld11: ImageButton
Hierbei ist nach "Feld" zuerst die Zeile und dann die Spalte des Elements angegeben.

dateZeit : Date, hier kann man die Funktion .toString() benutzen.

intKlicks: Integer, hier kann man die Funktion .toString() benutzen.

btnSpielen: ImageButton
btnRegeln: ImageButton
btnZurück: ImageButton

Wenn es ok ist, bitte schließen.
